#* Anyone who does contributes significantly to the project can request to be added to the funding list
#* Do open a issue for it, thought it will only be considered for significantly contributors, to avoid spam
github: ['akatsukilevi']

# TODO: Add Patreon & Ko-Fi links
# patreon: # Replace with a single Patreon username
